run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocritic
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/10yihang/autocache
  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: unexported-return

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
